/* 
 * Yahoo Finance Term Search API
 *
 * This is the API from yahoo finance to search for symbols.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kobeyoung81@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SearchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SearchResponseTests
    {
        // TODO uncomment below to declare an instance variable for SearchResponse
        //private SearchResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SearchResponse
            //instance = new SearchResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchResponse
        /// </summary>
        [Test]
        public void SearchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SearchResponse
            //Assert.IsInstanceOfType<SearchResponse> (instance, "variable 'instance' is a SearchResponse");
        }


        /// <summary>
        /// Test the property 'SuggestionTitleAccessor'
        /// </summary>
        [Test]
        public void SuggestionTitleAccessorTest()
        {
            // TODO unit test for the property 'SuggestionTitleAccessor'
        }
        /// <summary>
        /// Test the property 'SuggestionMeta'
        /// </summary>
        [Test]
        public void SuggestionMetaTest()
        {
            // TODO unit test for the property 'SuggestionMeta'
        }
        /// <summary>
        /// Test the property 'HiConf'
        /// </summary>
        [Test]
        public void HiConfTest()
        {
            // TODO unit test for the property 'HiConf'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

    }

}
