/* 
 * Yahoo Finance Term Search API
 *
 * This is the API from yahoo finance to search for symbols.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kobeyoung81@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing YahooTicker
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class YahooTickerTests
    {
        // TODO uncomment below to declare an instance variable for YahooTicker
        //private YahooTicker instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of YahooTicker
            //instance = new YahooTicker();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of YahooTicker
        /// </summary>
        [Test]
        public void YahooTickerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" YahooTicker
            //Assert.IsInstanceOfType<YahooTicker> (instance, "variable 'instance' is a YahooTicker");
        }


        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Exch'
        /// </summary>
        [Test]
        public void ExchTest()
        {
            // TODO unit test for the property 'Exch'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ExchDisp'
        /// </summary>
        [Test]
        public void ExchDispTest()
        {
            // TODO unit test for the property 'ExchDisp'
        }
        /// <summary>
        /// Test the property 'TypeDisp'
        /// </summary>
        [Test]
        public void TypeDispTest()
        {
            // TODO unit test for the property 'TypeDisp'
        }

    }

}
