/* 
 * Yahoo Finance API
 *
 * This is the API from yahoo finance to search for symbols and get quotes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kobeyoung81@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = YahooFinance.SearchTerm.Client.SwaggerDateConverter;

namespace YahooFinance.SearchTerm.Model
{
    /// <summary>
    /// QuoteResponseContentQuoteResponse
    /// </summary>
    [DataContract]
        public partial class QuoteResponseContentQuoteResponse :  IEquatable<QuoteResponseContentQuoteResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QuoteResponseContentQuoteResponse" /> class.
        /// </summary>
        /// <param name="result">result.</param>
        public QuoteResponseContentQuoteResponse(List<YahooQuote> result = default(List<YahooQuote>))
        {
            this.Result = result;
        }
        
        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [DataMember(Name="result", EmitDefaultValue=false)]
        public List<YahooQuote> Result { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QuoteResponseContentQuoteResponse {\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QuoteResponseContentQuoteResponse);
        }

        /// <summary>
        /// Returns true if QuoteResponseContentQuoteResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of QuoteResponseContentQuoteResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QuoteResponseContentQuoteResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Result == input.Result ||
                    this.Result != null &&
                    input.Result != null &&
                    this.Result.SequenceEqual(input.Result)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Result != null)
                    hashCode = hashCode * 59 + this.Result.GetHashCode();
                return hashCode;
            }
        }
    }
}
